social_simple/social_simple/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'),
]

social_simple/social_simple/communities/urls.py
from django.urls import path, re_path
from . import views

app_name = 'communities'

urlpatterns = [
    path('', views.ListCommunities.as_view(), name='all'),
    path('new/', views.CreateCommunity.as_view(), name='new'),
    re_path(
        r'^p/in/(?P<slug>[\w|-]+)',
        views.SingleCommunity.as_view(),
        name='single'),
    re_path(
        r'^join/(?P<slug>[\w|-]+)',
        views.JoinCommunity.as_view(),
        name='join'),
    re_path(
        r'^leave/(?P<slug>[\w|-]+)',
        views.LeaveCommunity.as_view(),
        name='leave'),
]

social_simple/social_simple/posts/urls.py
from django.urls import path, re_path
from . import views


app_name = 'posts'


urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='new'),
    re_path(
        r'^u/(?P<username>[-\w|-]+)/$',
        views.UserPosts.as_view(),
        name='for_user'),
    re_path(
        r'^u/(?P<username>[-\w|-]+)/(?P<pk>[\d]+)/$',
        views.PostDetail.as_view(),
        name='single'),
    re_path(
        r'^delete/(?P<pk>[\d]+)/$',
        views.DeletePost.as_view(),
        name='delete'),
]

social_simple/social_simple/social_simple/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('p/', include('posts.urls'), name='posts'),
    path('c/', include('communities.urls'), name='communities'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debug_toolbar/', include(debug_toolbar.urls))
    ] + urlpatterns

social_simple/social_simple/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'social_simple/css/master.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans" rel="stylesheet">  </head>
  <body>

    <nav class="navbar mynav" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a href="{% url 'posts:new' %}">Post</a></li>
          <li><a href="{% url 'communities:all' %}">Communities</a></li>
          <li><a href="{% url 'communities:new' %}">Create Community</a></li>
          <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'communities:all' %}">Communities</a></li>
          <li><a href="{% url 'accounts:login' %}">Log In</a></li>
          <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

  </body>

  <script type="text/javascript" src="{% static 'social_simple/js/master.js' %}">
  </script>
</html>

social_simple/social_simple/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome to Starsocial</h1>
{% endblock %}

social_simple/social_simple/templates/test.html
{% extends "base.html" %}

{% block content %}

  <h1>you are now logged in</h1>

{% endblock %}

social_simple/social_simple/templates/thanks.html
{% extends "base.html" %}

{% block content %}
<h1>Thanks for visiting, have a good one!</h1>
{% endblock %}