social_simple/social_simple/communities/urls.py
from django.urls import path, re_path
from . import views

app_name = 'communities'

urlpatterns = [
    path('', views.ListCommunities.as_view(), name='all'),
    path('new/', views.CreateCommunity.as_view(), name='new'),
    re_path(
        r'^p/in/(?P<slug>[\w|-]+)',
        views.SingleCommunity.as_view(),
        name='single'),
    re_path(
        r'^join/(?P<slug>[\w|-]+)',
        views.JoinCommunity.as_view(),
        name='join'),
    re_path(
        r'^leave/(?P<slug>[\w|-]+)',
        views.LeaveCommunity.as_view(),
        name='leave'),
]

social_simple/social_simple/posts/urls.py
from django.urls import path, re_path
from . import views


app_name = 'posts'


urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='new'),
    re_path(
        r'^u/(?P<username>[-\w|-]+)/$',
        views.UserPosts.as_view(),
        name='for_user'),
    re_path(
        r'^u/(?P<username>[-\w|-]+)/(?P<pk>[\d]+)/$',
        views.PostDetail.as_view(),
        name='single'),
    re_path(
        r'^delete/(?P<pk>[\d]+)/$',
        views.DeletePost.as_view(),
        name='delete'),
]

social_simple/social_simple/social_simple/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('p/', include('posts.urls'), name='posts'),
    path('c/', include('communities.urls'), name='communities'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debug_toolbar/', include(debug_toolbar.urls))
    ] + urlpatterns

social_simple/social_simple/posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
import misaka
from communities.models import Community

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete='SET_NULL')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    community = models.ForeignKey(
        Community,
        related_name='posts',
        null=True,
        blank=True,
        on_delete='SET_NULL')

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={
            'username': self.user.username,
            'pk': self.pk})

    class Meta():
        ordering = ['-created_at']
        unique_together = ['user', 'message']

social_simple/social_simple/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'community')


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related(
                'posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user

        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'community')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'community')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'community')

    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post deleted!')
        return super().delete(*args, **kwargs)

social_simple/social_simple/posts/templates/posts/_post.html
<div class="post media">
  <h3>{{post.message_html|safe}}</h3>
  <div class="media-body">
    <h5 class="media-heading">
      <span class="username">
        <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
      </span>
      <time class="time">
        <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
          {{post.created_at}}
        </a>

      </time>
    </h5>

    <div class="media-footer">
      {% if user.is_authenticated and post.user == user %}
      <a class="btn btn-simple" href="{% url 'posts:delete' pk=post.pk %}" title="delete">
        <span class="glyphicon glyphicon-remove text-danger" aria-hidden='true'></span>
        <span class="text-danger icon-label">Delete</span>
      </a>
      {% endif %}

    </div>
  </div>
</div>

social_simple/social_simple/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">

  <div class="container">

    <div class="row">
      {% block prepost %}

      {% endblock %}

      {% block post_content %}

      {% endblock %}

      {% block postpost %}

      {% endblock %}
    </div>

  </div>

</div>
{% endblock %}

social_simple/social_simple/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}

  <h3>Are you sure you want to delete this post?</h3>

  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>
  <form method="post">
    {% csrf_token %}
    <input class="btn btn-large btn-danger" type="submit" value="Delete">
    <a  class="btn btn-simple btn-large btn-default"
        href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
  </form>

{% endblock %}

social_simple/social_simple/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

<div class="col-md-4">
  {% if user.is_authenticated %}
  <div class="card card-with-shadow">

    <div class="content">

      <h5>Your Communities</h5>
      <ul class="list-unstyled">
        {% for membership in get_user_communities %}
        <li class="community li-with-bullet">
          <a href="{% url 'communities:single' slug=membership.community.slug %}"></a>
        </li>
        {% endfor %}
      </ul>

    </div>

  </div>
  {% endif %}
</div>

{% block post_content %}

<div class="col-md-8">
  {% include "posts/_post.html" %}
</div>

{% endblock %}

social_simple/social_simple/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}
<h3>Create a new Post</h3>
<form id='postForm' action="{% url 'posts:new' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-large btn-primary" type="submit" value="Create">
</form>

{% endblock %}

social_simple/social_simple/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
  {% if user.is_authenticated %}
  <div class="card card-with-shadow">

    <div class="content">

      <h5>Your Communities</h5>
      <ul class="list-unstyled">
        {% for membership in get_user_communities %}
        <li class="community li-with-bullet">
          <a href="{% url 'communities:single' slug=membership.community.slug %}"></a>
        </li>
        {% endfor %}
      </ul>

    </div>

  </div>
  {% endif %}

  <div class="card card-with-shadow">

    <div class="content">

      <h5>All Communities</h5>
      <ul class="list-unstyled">
        {% for other_community in get_other_communities %}
        <li class="community li-with-bullet">
          <a href="{% url 'communities:all' slug=other_community.slug %}"></a>
        </li>
        {% endfor %}
      </ul>

    </div>

  </div>

</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}
</div>
{% endblock %}

social_simple/social_simple/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
  <h1>@{{post_user.username}}</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}
</div>
{% endblock %}