social_simple/social_simple/communities/urls.py
from django.urls import path, re_path
from . import views

app_name = 'communities'

urlpatterns = [
    path('', views.ListCommunities.as_view(), name='all'),
    path('new/', views.CreateCommunity.as_view(), name='new'),
    re_path(
        r'^p/in/(?P<slug>[\w|-]+)',
        views.SingleCommunity.as_view(),
        name='single'),
    re_path(
        r'^join/(?P<slug>[\w|-]+)',
        views.JoinCommunity.as_view(),
        name='join'),
    re_path(
        r'^leave/(?P<slug>[\w|-]+)',
        views.LeaveCommunity.as_view(),
        name='leave'),
]

social_simple/social_simple/posts/urls.py
from django.urls import path, re_path
from . import views


app_name = 'posts'


urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='new'),
    re_path(
        r'^u/(?P<username>[-\w|-]+)/$',
        views.UserPosts.as_view(),
        name='for_user'),
    re_path(
        r'^u/(?P<username>[-\w|-]+)/(?P<pk>[\d]+)/$',
        views.PostDetail.as_view(),
        name='single'),
    re_path(
        r'^delete/(?P<pk>[\d]+)/$',
        views.DeletePost.as_view(),
        name='delete'),
]

social_simple/social_simple/social_simple/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('p/', include('posts.urls'), name='posts'),
    path('c/', include('communities.urls'), name='communities'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks', views.ThanksPage.as_view(), name='thanks'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('debug_toolbar/', include(debug_toolbar.urls))
    ] + urlpatterns

social_simple/social_simple/communities/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse

User = get_user_model()
register = template.Library()


class Community(models.Model):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='Member')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super(Community, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('communities:single', kwargs={'slug': self.slug})

    class Meta():
        ordering = ['name']


class Member(models.Model):
    community = models.ForeignKey(
        Community,
        related_name='memberships',
        on_delete='SET_NULL')
    user = models.ForeignKey(
        User,
        related_name='user_communities',
        on_delete='SET_NULL')

    def __str__(self):
        return self.user.username

    class Meta():
        unique_together = ('community', 'user')

social_simple/social_simple/communities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Community, Member
from django.views import generic
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
# Create your views here.


class CreateCommunity(LoginRequiredMixin,
                      generic.CreateView):
    permission_required = True
    model = Community
    fields = ['name', 'description']


class SingleCommunity(generic.DetailView):
    model = Community


class ListCommunities(generic.ListView):
    model = Community


class JoinCommunity(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('communities:single', kwargs={
            'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        community = get_object_or_404(
            Community,
            slug=self.kwargs.get('slug'))

        try:
            Member.objects.create(user=self.request.user, community=community)
        except IntegrityError:
            messages.warning(self.request, ("Already a member!"))
        else:
            messages.success(self.request, ('You are now a member!'))

        return super().get(request, *args, **kwargs)


class LeaveCommunity(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('communities:single', kwargs={
            'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = Member.objects.filter(
                user=self.request.user,
                community__slug=self.kwargs.get('slug')
            ).get()
        except Member.DoesNotExist:
            messages.warning(self.request, ("You are not a member!"))
        else:
            membership.delete()
            messages.success(self.request, ('You left the community :(!'))

        return super().get(request, *args, **kwargs)

social_simple/social_simple/communities/templates/communities/community_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    {% block precommunity %}{% endblock %}
    {% block community_content %}{% endblock %}
    {% block postcommunity%}{% endblock %}
  </div>
</div>
{% endblock %}

social_simple/social_simple/communities/templates/communities/community_detail.html
{% extends "communities/community_base.html" %}

{% block precommunity %}
<h1>{{community.name}}</h1>
<h2>Member Count {{community.members.count}}</h2>

<div class="content">
  {% if user in community.members.all %}
  <a href="{% url 'communities:leave' slug=community.slug %}"
     class="btn btn-large btn-warning">
     <span class="glyphicon glyphicon-remove"></span>Leave
   </a>
   {% else %}
   <a href="{% url 'communities:join' slug=community.slug %}"
      class="btn btn-large btn-fill btn-primary">
      <span class="glyphicon glyphicon-ok"></span>Join
    </a>
  {% endif %}
</div>
{% endblock %}

{% block community_content %}
<div class="col-md-8">
  {% if community.posts.count == 0 %}
  <h2>No posts yet!</h2>
  {% else %}
  {% for post in community.posts.all %}
    {% include "posts/_post.html" %}
  {% endfor %}
  {% endif %}
</div>
{% endblock %}

social_simple/social_simple/communities/templates/communities/community_form.html
{% extends "communities/community_base.html" %}
{% load bootstrap3 %}

{% block community_content %}
<h4>Create new Group</h4>

<form action="{% url 'communities:new' %}" method="post" id="communityForm">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-md btn-primary" type="submit" value="New Community">
</form>

{% endblock %}

social_simple/social_simple/communities/templates/communities/community_list.html
{% extends "communities/community_base.html" %}

{% block precommunity %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
    <h2>
      Welcome back!
      <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
    </h2>
    {% endif %}
    <h2>Groups</h2>
    <h5>Welcome to the groups page!</h2>
  </div>

  {% if user.is_authenticated %}
  <a class="btn btn-md btn-fill btn-warning"
     href="{% url 'communities:new' %}">
    <span class="glpyhicon glyphicon-plus"> New Group</span><a/>
  {% endif %}
</div>
{% endblock %}

{% block community_content %}
<div class="col-md-8">
  <div class="list-group">
    {% for community in object_list %}

      <a class="list-group-item" href="{% url 'communities:single' slug=community.slug %}">

        <h3 class="title list-group-item-heading">{{community.name}}</h3>

        <div class="list-group-item-text container-fluid">
          {{community.description_html|safe}}
          <div class="row">
            <div class="col-md-4">
              <span class="badge">{{community.members.count}}</span>
              member{{community.members.count|pluralize}}
            </div>
            <div class="col-md-4">
              <span class="badge">{{community.posts.count}}</span>
              post{{community.posts.count|pluralize}}
            </div>
          </div>
        </div>

      </a>
    {% endfor %}
  </div>
</div>
{% endblock %}